@startuml
annotation java.lang.Override
class interfaz.VentanaPrincipal
class java.io.FileNotFoundException
class java.io.PrintWriter
class java.lang.Math
class java.nio.file.Paths
class java.time.LocalDate
class java.time.format.DateTimeFormatter
class java.util.ArrayList
class java.util.HashMap
class java.util.Iterator
class java.util.Map
class java.util.Map.Entry
class java.util.Objects
class java.util.Scanner
class java.util.logging.Level
class java.util.logging.Logger
class proyectofitness.Cedula
class proyectofitness.Correo
class proyectofitness.Dia
class proyectofitness.Ejercicio
class proyectofitness.Maquinas
class proyectofitness.Mediciones
class proyectofitness.Paciente
class proyectofitness.Pacientes
class proyectofitness.ProgramaEntrenamiento
class proyectofitness.ProyectoFitness
class proyectofitness.Telefono
class proyectofitness.TipoEjercicio
class proyectofitness.TiposEjercicio
class proyectofitness.TiposMedicion
proyectofitness.Cedula ..> java.lang.Override
proyectofitness.Cedula ..> java.util.Objects
proyectofitness.Dia ..> java.lang.Override
proyectofitness.Dia --|> java.util.HashMap
proyectofitness.Ejercicio ..> java.lang.Override
proyectofitness.Maquinas ..> java.lang.Override
proyectofitness.Maquinas --|> java.util.HashMap
proyectofitness.Mediciones ..> java.lang.Override
proyectofitness.Mediciones ..> java.lang.Math
proyectofitness.Mediciones --|> java.util.HashMap
proyectofitness.Paciente ..> java.lang.Override
proyectofitness.Paciente ..> java.time.LocalDate
proyectofitness.Pacientes ..> java.lang.Override
proyectofitness.Pacientes ..> java.util.ArrayList
proyectofitness.Pacientes --|> java.util.HashMap
proyectofitness.Pacientes ..> java.util.Iterator
proyectofitness.ProgramaEntrenamiento ..> java.lang.Override
proyectofitness.ProgramaEntrenamiento ..> java.time.LocalDate
proyectofitness.ProgramaEntrenamiento --|> java.util.HashMap
proyectofitness.ProyectoFitness ..> interfaz.VentanaPrincipal
proyectofitness.ProyectoFitness ..> java.io.FileNotFoundException
proyectofitness.ProyectoFitness ..> java.io.PrintWriter
proyectofitness.ProyectoFitness ..> java.nio.file.Paths
proyectofitness.ProyectoFitness ..> java.time.LocalDate
proyectofitness.ProyectoFitness ..> java.time.format.DateTimeFormatter
proyectofitness.ProyectoFitness ..> java.util.ArrayList
proyectofitness.ProyectoFitness ..> java.util.Iterator
proyectofitness.ProyectoFitness ..> java.util.Map
proyectofitness.ProyectoFitness ..> java.util.Map.Entry
proyectofitness.ProyectoFitness ..> java.util.Scanner
proyectofitness.ProyectoFitness ..> java.util.logging.Level
proyectofitness.ProyectoFitness ..> java.util.logging.Logger
proyectofitness.TipoEjercicio ..> java.lang.Override
proyectofitness.TiposEjercicio ..> java.lang.Override
proyectofitness.TiposEjercicio ..> java.util.ArrayList
proyectofitness.TiposEjercicio --|> java.util.HashMap
proyectofitness.TiposEjercicio ..> java.util.Iterator
proyectofitness.TiposEjercicio ..> java.util.Map
proyectofitness.TiposMedicion ..> java.lang.Override
proyectofitness.TiposMedicion --|> java.util.HashMap
@enduml